//
// Generated file, do not edit! Created by nedtool 4.6 from Frame.msg.
//

#ifndef _FRAME_M_H_
#define _FRAME_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Frame.msg:3</tt> by nedtool.
 * <pre>
 * //Message type to represent frame request of LIN
 * message Frame extends cMessage
 * {
 *     int STEI; // Source Terminal Equipment Identifier
 *     int DTEI; // Destinations Terminal Equipment Identifier 
 * }
 * </pre>
 */
class Frame : public ::cMessage
{
  protected:
    int STEI_var;
    int DTEI_var;

  private:
    void copy(const Frame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Frame&);

  public:
    Frame(const char *name=NULL, int kind=0);
    Frame(const Frame& other);
    virtual ~Frame();
    Frame& operator=(const Frame& other);
    virtual Frame *dup() const {return new Frame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSTEI() const;
    virtual void setSTEI(int STEI);
    virtual int getDTEI() const;
    virtual void setDTEI(int DTEI);
};

inline void doPacking(cCommBuffer *b, Frame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Frame& obj) {obj.parsimUnpack(b);}


#endif // ifndef _FRAME_M_H_

